# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import factorization_pb2 as factorization__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in factorization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrimeFactorizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrimeFactors = channel.unary_unary(
                '/PrimeFactorizationService/GetPrimeFactors',
                request_serializer=factorization__pb2.NumberRequest.SerializeToString,
                response_deserializer=factorization__pb2.PrimeFactorsResponse.FromString,
                _registered_method=True)
        self.GetPrimeFactorsStream = channel.stream_stream(
                '/PrimeFactorizationService/GetPrimeFactorsStream',
                request_serializer=factorization__pb2.NumberRequest.SerializeToString,
                response_deserializer=factorization__pb2.PrimeFactorsResponse.FromString,
                _registered_method=True)


class PrimeFactorizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrimeFactors(self, request, context):
        """Requête/Réponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrimeFactorsStream(self, request_iterator, context):
        """Flux bidirectionnel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimeFactorizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrimeFactors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimeFactors,
                    request_deserializer=factorization__pb2.NumberRequest.FromString,
                    response_serializer=factorization__pb2.PrimeFactorsResponse.SerializeToString,
            ),
            'GetPrimeFactorsStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPrimeFactorsStream,
                    request_deserializer=factorization__pb2.NumberRequest.FromString,
                    response_serializer=factorization__pb2.PrimeFactorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PrimeFactorizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PrimeFactorizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrimeFactorizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrimeFactors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrimeFactorizationService/GetPrimeFactors',
            factorization__pb2.NumberRequest.SerializeToString,
            factorization__pb2.PrimeFactorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrimeFactorsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/PrimeFactorizationService/GetPrimeFactorsStream',
            factorization__pb2.NumberRequest.SerializeToString,
            factorization__pb2.PrimeFactorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
